# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"url_path_query": "00_core.ipynb",
         "url_pgs_cntry": "00_core.ipynb",
         "url_pgs_cntry.__doc__": "00_core.ipynb",
         "url_pg_cntry": "00_core.ipynb",
         "url_pg_cntry.__doc__": "00_core.ipynb",
         "url_upgs_cntry": "00_core.ipynb",
         "url_upgs_cntry.__doc__": "00_core.ipynb",
         "url_upgotd": "00_core.ipynb",
         "url_upgotd.__doc__": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://kdorichev.github.io/joshuaproject/"

git_url = "https://github.com/kdorichev/joshuaproject/tree/master/"

def custom_doc_links(name): return None
